version: '3'

services:
  postgresql:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"

  django:
    image: docker.io/library/ecdjago:latest
    ports:
    - "8000:8000"
