variable "ENV" {}
variable "PREFIX" {}
variable "AWS_REGION" {}
variable "DEFAULT_TAGS" {}
variable "VPC_ID" {}
variable "PUBLIC_SUBNETS" {}
variable "PRIVATE_SUBNETS" {}
variable "ALB_SG_ID" {}
variable "DJANGO_SG_ID" {}
variable "ALB_DEPEND" {}
variable "ALB_TARGET_GROUP" {}
variable "ECR_REPO_URL" {}
variable "ECS_TASK_ROLE" {}
