# Generated by Django 3.2.5 on 2021-08-01 07:45

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='郵便番号が仕様(150-0000)と異なります。', regex=re.compile('(1-9)(0-9){2}-(0-9){4}'))], verbose_name='postal code'),
        ),
    ]
